<?php
if (isset($flash['success']) && !empty($flash['success'])):
    foreach ($flash['success'] as $message):
?>
        <div class="alert alert-success" role="alert">
            <?= htmlspecialchars($message) ?>
        </div>
    <?php
    endforeach;
endif;
if (isset($flash['errors']) && !empty($flash['errors'])):
    foreach ($flash['errors'] as $error):
    ?>
        <div class="alert alert-danger" role="alert">
            <?= htmlspecialchars($error) ?>
        </div>
<?php
    endforeach;
endif;
?>
<div class="container-lg mt-3">
    <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url->getId()) ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url->getName()) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url->getCreatedDT()) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <h2 class="mt-5 mb-3">Проверки</h2>
    <form method="post" action="/urls/<?= htmlspecialchars($url->getId()) ?>/checks">
        <input type="submit" class="btn btn-primary" value="Запустить проверку">
    </form>
    <table class="table table-bordered table-hover" data-test="checks">
        <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($checks as $check): ?>
                <tr>
                    <td><?= htmlspecialchars($check->getId()) ?></td>
                    <td><?= htmlspecialchars($check->getStatusCode()) ?></td>
                    <td class="text-break"><?= htmlspecialchars($check->getH1()) ?></td>
                    <td class="text-break"><?= htmlspecialchars($check->getTitle()) ?></td>
                    <td class="text-break"><?= htmlspecialchars($check->getDescription()) ?></td>
                    <td><?= htmlspecialchars($check->getCreatedDT()) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>